version: "3.7"

services:
  database:
    container_name: mysql_container
    restart: always
    build: ./DataBase
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./DataBase/mysql/sql:/docker-entrypoint-initdb.d
      - ./DataBase/mysql/config:/etc/mysql/conf.d
      - ./DataBase/mysql/:/var/lib/mysql

  backend:
    container_name: spring_container
    restart: always
    build: ./BackEnd
    ports:
      - "8080:8080"
    volumes:
      - ./BackEnd:/app
    command:
      - pwd
    environment:
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://database:3306/sample?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
      spring.datasource.username: ${MYSQL_USER}
      spring.datasource.password: ${MYSQL_PASSWORD}
