version: "3.7"

services:
  database:
    container_name: mysql_container
    restart: always
    build:
      context: ./DataBase/mysql
      dockerfile: Dockerfile
    hostname: database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./DataBase/mysql/sql:/docker-entrypoint-initdb.d
      - ./DataBase/mysql/config:/etc/mysql/conf.d

  backend:
    container_name: spring_container
    restart: always
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      # for remote debug
      - "5005:5005"
    volumes:
      - ./BackEnd:/app
    environment:
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://database/starter?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
      spring.datasource.username: ${MYSQL_USER}
      spring.datasource.password: ${MYSQL_PASSWORD}
